# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a20f1c08d203092ddd6ad3111b8572d792fe70fd555f6880a58b6430a5b3b5a596de2bb534f47789a791bdc3137d4cf062d4374079ac4f662c163a690c00a13

test:
  secret_key_base: 78f3e048a2dac731dee0518f7b556e2d9f260a746d27caca59f59de13e4bc449e936c67d7960c8324d12ee4f27916abe101dcfbcf7cb735c038255343b0f44cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
